datasource:
  postgres:
    url: jdbc:postgresql://192.168.56.1:5432/petclinic
    username:
    password:
    driverClassName: org.postgresql.Driver    

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
      
spring.metrics.export.send-latest: false
spring.metrics.export.delay-millis: 30000